export const TRADITIONAL_CATEGORY = ['CNBC', 'BBC', 'REUTERS'];
export const CRYPTO_CATEGORY = ['COINDESK', 'COINTELEGRAPH', 'CRYPTOSLATE'];
export const FINANCIAL_INDEX = ['DOW', 'NASDAQ', 'VIX', 'CRYPTO # GREED & FEAR', 'BITCOIN'];